title: Light Between Worlds
description: Stories from Ellara's world

# Theme settings
remote_theme: patdryburgh/hitchens
dark_mode: true

# Blog settings
paginate: 10
date_format: "%B %d, %Y"

sass:
  sass_dir: assets/css
  style: compressed

# Enable heading anchors
heading_anchors: true

# Footer content
footer_content: "Copyright &copy; 2025"

# Aux links for the upper right navigation
aux_links:
  "Return Home":
    - "/"

# Makes Aux links open in a new tab
aux_links_new_tab: true

# Enable search
search_enabled: true